# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jaz/Escritorio/jaz/fiuba/taller/tp4/worms

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jaz/Escritorio/jaz/fiuba/taller/tp4/worms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jaz/Escritorio/jaz/fiuba/taller/tp4/worms/CMakeFiles /home/jaz/Escritorio/jaz/fiuba/taller/tp4/worms/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jaz/Escritorio/jaz/fiuba/taller/tp4/worms/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tp

# Build rule for target.
tp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tp
.PHONY : tp

# fast build rule for target.
tp/fast:
	$(MAKE) -f CMakeFiles/tp.dir/build.make CMakeFiles/tp.dir/build
.PHONY : tp/fast

Beam.o: Beam.cpp.o

.PHONY : Beam.o

# target to build an object file
Beam.cpp.o:
	$(MAKE) -f CMakeFiles/tp.dir/build.make CMakeFiles/tp.dir/Beam.cpp.o
.PHONY : Beam.cpp.o

Beam.i: Beam.cpp.i

.PHONY : Beam.i

# target to preprocess a source file
Beam.cpp.i:
	$(MAKE) -f CMakeFiles/tp.dir/build.make CMakeFiles/tp.dir/Beam.cpp.i
.PHONY : Beam.cpp.i

Beam.s: Beam.cpp.s

.PHONY : Beam.s

# target to generate assembly for a file
Beam.cpp.s:
	$(MAKE) -f CMakeFiles/tp.dir/build.make CMakeFiles/tp.dir/Beam.cpp.s
.PHONY : Beam.cpp.s

Worm.o: Worm.cpp.o

.PHONY : Worm.o

# target to build an object file
Worm.cpp.o:
	$(MAKE) -f CMakeFiles/tp.dir/build.make CMakeFiles/tp.dir/Worm.cpp.o
.PHONY : Worm.cpp.o

Worm.i: Worm.cpp.i

.PHONY : Worm.i

# target to preprocess a source file
Worm.cpp.i:
	$(MAKE) -f CMakeFiles/tp.dir/build.make CMakeFiles/tp.dir/Worm.cpp.i
.PHONY : Worm.cpp.i

Worm.s: Worm.cpp.s

.PHONY : Worm.s

# target to generate assembly for a file
Worm.cpp.s:
	$(MAKE) -f CMakeFiles/tp.dir/build.make CMakeFiles/tp.dir/Worm.cpp.s
.PHONY : Worm.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/tp.dir/build.make CMakeFiles/tp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/tp.dir/build.make CMakeFiles/tp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/tp.dir/build.make CMakeFiles/tp.dir/main.cpp.s
.PHONY : main.cpp.s

stage.o: stage.cpp.o

.PHONY : stage.o

# target to build an object file
stage.cpp.o:
	$(MAKE) -f CMakeFiles/tp.dir/build.make CMakeFiles/tp.dir/stage.cpp.o
.PHONY : stage.cpp.o

stage.i: stage.cpp.i

.PHONY : stage.i

# target to preprocess a source file
stage.cpp.i:
	$(MAKE) -f CMakeFiles/tp.dir/build.make CMakeFiles/tp.dir/stage.cpp.i
.PHONY : stage.cpp.i

stage.s: stage.cpp.s

.PHONY : stage.s

# target to generate assembly for a file
stage.cpp.s:
	$(MAKE) -f CMakeFiles/tp.dir/build.make CMakeFiles/tp.dir/stage.cpp.s
.PHONY : stage.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... tp"
	@echo "... edit_cache"
	@echo "... Beam.o"
	@echo "... Beam.i"
	@echo "... Beam.s"
	@echo "... Worm.o"
	@echo "... Worm.i"
	@echo "... Worm.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... stage.o"
	@echo "... stage.i"
	@echo "... stage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

