gravity: 9.8
time_step: 0.1 
velocity_iterations: 8
position_iterations: 3
wind: 2

beam_width: 6
beam_height: 0.8
beam_friction: 1

worm_turn_time: 40
worm_initial_life: 100
worm_walk_velocity: 50
worm_jump_velocity: -7
worm_density: 1
worm_size: 1.6
worm_friction: 1

weapon_size: 1.5
weapon_density: 1
explosion_power: 50
bazooka_damage: 50
bazooka_radius: 2
