gravity: 9.8
time_step: 0.1 
velocity_iterations: 8
position_iterations: 3
wind: 0.5

beam_width: 0.8
beam_height: 3

worm_initial_life: 100
worm_walk_velocity: 5
worm_jump_velocity: -7
worm_density: 1
worm_size: 0.8

weapon_size: 0.1
weapon_density: 1
bazooka_damage: 50
bazooka_radius: 2
