gravity: 9.8
time_step: 0.1 
velocity_iterations: 8
position_iterations: 3

worm_initial_life: 25
worm_walk_velocity: 5
worm_density: 1
worm_size: 1

weapon_size: 0.1
weapon_density: 1
bazooka_damage: 50
bazooka_radius: 2
